if: tag IS blank # don't build tags
sudo: true # travis-ci/travis-ci#9033
os: linux
language: cpp
compiler: gcc
notifications:
  email:
    on_success: change
    on_failure: always
git:
  depth: 5

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

matrix:
  include:
    # GCC 5
    - dist: xenial

    # GCC 7
    - dist: bionic

    # Clang
    - compiler: clang
      env: ADDITIONAL_CXX_FLAGS="-g -fno-omit-frame-pointer -fsanitize=address,undefined"

    # Xcode Clang
    - env: ADDITIONAL_CXX_FLAGS="-g -fno-omit-frame-pointer -fsanitize=address,undefined"
      os: osx

script:
  # sanitize options
  - export ASAN_OPTIONS=allow_addr2line=true:check_initialization_order=true:strict_init_order=true:strict_string_checks=true:detect_odr_violation=2:detect_stack_use_after_return=true:verbosity=0
  # tests
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="${ADDITIONAL_CXX_FLAGS}"
  - make -j
  - ctest --output-on-failure
